name: DOCKER-HUB

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [ master ]
    release:
        types: [ published ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code
                uses: actions/checkout@v2
            -   name: Set up node
                uses: actions/setup-node@v2
                with:
                    node-version: '12.16'
            -   name: Install dependencies
                run: yarn install:all
            -   name: Run tests
                run: yarn test:all
            -   name: Build
                run: yarn build:all
            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -   name: Push Latest
                if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
                run: |
                    docker push scale8/router:latest && docker push scale8/api:latest && docker push scale8/edge:latest
            -   name: Tag for Release
                if: github.event_name == 'release'
                run: |
                    docker tag scale8/router:latest scale8/router:${GITHUB_REF##*/} && docker tag scale8/api:latest scale8/api:${GITHUB_REF##*/} && docker tag scale8/edge:latest scale8/edge:${GITHUB_REF##*/}
            -   name: Push for Release
                if: github.event_name == 'release'
                run: |
                    docker push scale8/router:${GITHUB_REF##*/} && docker push scale8/api:${GITHUB_REF##*/} && docker push scale8/edge:${GITHUB_REF##*/}
